#### Extraction : Data exctracted into json format

#### Transformation : Data transformation

### Aggregated Insaurance

In [1]:
import json 
import os 
import pandas as pd
import _sqlite3

In [2]:
file = os.listdir('../pulse/data/aggregated/insurance/country/india')
file

['2020', '2021', '2022', '2023', '2024', 'state']

In [3]:
# table schema:
# - Name
# - type
# - count
# - amount
# - level (country/state)
# - region (India/Maharashtra,Gujrat)
# - Year
# - quater

In [4]:
from datetime import datetime,UTC
second=1585679400000/1000
date=datetime.fromtimestamp(second,UTC)
formatted = date.strftime("%d-%m-%Y %H:%M:%S")
print(formatted)

31-03-2020 18:30:00

In [5]:
file_state = os.listdir('../pulse/data/aggregated/insurance/country/india/state')
file[:5]

['2020', '2021', '2022', '2023', '2024']

In [6]:
file_state_assam = os.listdir('../pulse/data/aggregated/insurance/country/india/state/assam')
file_state_assam

['2020', '2021', '2022', '2023', '2024']

In [7]:
file1 = os.listdir('../pulse/data/aggregated/insurance/country/india/state/assam/2020')
file1

['2.json', '3.json', '4.json']

In [8]:
path="../pulse/data/aggregated/insurance/country/india/state/assam/2020"

In [9]:
path.split("/")[-1]

'2020'

In [10]:
root_path="../pulse/data/aggregated/insurance/country/india"
root=os.listdir("../pulse/data/aggregated/insurance/country/india/state/assam")
root[:5]

['2020', '2021', '2022', '2023', '2024']

In [11]:
root_path = "../pulse/data/aggregated/insurance/country/india"
entries = os.listdir(root_path)
print(entries)
ind=0
aggregate_insurance=pd.DataFrame(columns=["name","insurancetype","insurancecount","insuranceamount","level","region","year","quater"])
for entry in entries:
    if entry != "state": 
        level = "India"
        regionlevel = "India"
        year = entry
        year_path = os.path.join(root_path, year)

        files = os.listdir(year_path)
        for file_name in files:
            try:
                file_path = os.path.join(year_path, file_name)
                with open(file_path, "r") as file:
                    response = json.load(file)

                for item in response["data"]["transactionData"]:
                    name = item["name"]
                    for instrument in item["paymentInstruments"]:
                        type = instrument["type"]
                        count = instrument["count"]
                        amount = instrument["amount"]
                        quarter = file_name.split(".")[0]
                        aggregate_insurance.loc[ind]=[name,type,count,amount,level,regionlevel,year,quarter]
                        ind+=1

            except Exception as e:
                print("Country error:", file_path, e)

    else:  
        level = "state"
        state_root = os.path.join(root_path, "state")
        states = os.listdir(state_root)

        for state_name in states:
            state_path = os.path.join(state_root, state_name)
            regionlevel=state_name
            if os.path.isdir(state_path):
                for year in os.listdir(state_path):
                    year_path = os.path.join(state_path, year)

                    if os.path.isdir(year_path):
                        for file_name in os.listdir(year_path):
                            try:
                                file_path = os.path.join(year_path, file_name)
                                with open(file_path, "r") as file:
                                    response = json.load(file)

                                for item in response["data"]["transactionData"]:
                                    name = item["name"]
                                    for instrument in item["paymentInstruments"]:
                                        type = instrument["type"]
                                        count = instrument["count"]
                                        amount = instrument["amount"]
                                        quarter = file_name.split(".")[0]
                                        aggregate_insurance.loc[ind]=[name,type,count,amount,level,regionlevel,year,quarter]
                                        ind+=1

                            except Exception as e:
                                print("State error:", file_path, e)
                                
aggregate_insurance

['2020', '2021', '2022', '2023', '2024', 'state']

,name,insurancetype,insurancecount,insuranceamount,level,region,year,quater
0,Insurance,TOTAL,185348,33732166.0,India,India,2020,2
1,Insurance,TOTAL,354284,89495076.0,India,India,2020,3
2,Insurance,TOTAL,248626,170979933.0,India,India,2020,4
3,Insurance,TOTAL,318119,206307024.0,India,India,2021,1
4,Insurance,TOTAL,363989,295066678.0,India,India,2021,2
...,...,...,...,...,...,...,...,...
696,Insurance,TOTAL,72712,100365562.0,state,west-bengal,2023,4
697,Insurance,TOTAL,79576,104987909.0,state,west-bengal,2024,1
698,Insurance,TOTAL,67048,89476633.0,state,west-bengal,2024,2
699,Insurance,TOTAL,77158,107451766.0,state,west-bengal,2024,3
700,Insurance,TOTAL,91719,120602777.0,state,west-bengal,2024,4

In [12]:
data1=aggregate_insurance
data1.shape

(701, 8)

In [13]:
rootyear=os.listdir(os.path.join(root_path,"2020"))
rootyear

['2.json', '3.json', '4.json']

### Aggregated transaction

In [14]:
root_path="../pulse/data/aggregated/transaction/country/india"
entries=os.listdir(root_path)
print(entries)
ind=0
aggregate_transaction=pd.DataFrame(columns=["name","insurancetype","insurancecount","insuranceamount","level","region","year","quater"])
for entry in entries:
    if entry!="state":
        level="state"
        year=entry
        year_path = os.path.join(root_path, year)
        files = os.listdir(year_path)
        for file_name in files:
            try:
                file_path = os.path.join(year_path, file_name)
                with open(file_path, "r") as file:
                    response = json.load(file)

                for item in response["data"]["transactionData"]:
                    name = item["name"]
                    for instrument in item["paymentInstruments"]:
                        type = instrument["type"]
                        count = instrument["count"]
                        amount = instrument["amount"]
                        quarter = file_name.split(".")[0]
                        aggregate_transaction.loc[ind]=[name,type,count,amount,level,regionlevel,year,quarter]
                        ind+=1

            except Exception as e:
                print("Country error:", file_path, e)

    else:  
        level = "state"
        state_root = os.path.join(root_path, "state")
        states = os.listdir(state_root)

        for state_name in states:
            state_path = os.path.join(state_root, state_name)
            regionlevel=state_name
            if os.path.isdir(state_path):
                for year in os.listdir(state_path):
                    year_path = os.path.join(state_path, year)

                    if os.path.isdir(year_path):
                        for file_name in os.listdir(year_path):
                            try:
                                file_path = os.path.join(year_path, file_name)
                                with open(file_path, "r") as file:
                                    response = json.load(file)

                                for item in response["data"]["transactionData"]:
                                    name = item["name"]
                                    for instrument in item["paymentInstruments"]:
                                        type = instrument["type"]
                                        count = instrument["count"]
                                        amount = instrument["amount"]
                                        quarter = file_name.split(".")[0]
                                        aggregate_transaction.loc[ind]=[name,type,count,amount,level,regionlevel,year,quarter]
                                        ind+=1

                            except Exception as e:
                                print("State error:", file_path, e)
                                
aggregate_transaction

['2018', '2019', '2020', '2021', '2022', '2023', '2024', 'state']

,name,insurancetype,insurancecount,insuranceamount,level,region,year,quater
0,Recharge & bill payments,TOTAL,72550406,1.447271e+10,state,west-bengal,2018,1
1,Peer-to-peer payments,TOTAL,46982705,1.472459e+11,state,west-bengal,2018,1
2,Merchant payments,TOTAL,5368669,4.656679e+09,state,west-bengal,2018,1
3,Financial Services,TOTAL,3762820,8.158531e+08,state,west-bengal,2018,1
4,Others,TOTAL,5761576,4.643217e+09,state,west-bengal,2018,1
...,...,...,...,...,...,...,...,...
5169,Merchant payments,TOTAL,655100809,3.892862e+11,state,west-bengal,2024,4
5170,Peer-to-peer payments,TOTAL,493217788,1.361927e+12,state,west-bengal,2024,4
5171,Recharge & bill payments,TOTAL,76043195,5.753406e+10,state,west-bengal,2024,4
5172,Financial Services,TOTAL,2352084,8.472965e+08,state,west-bengal,2024,4
5173,Others,TOTAL,421806,5.053641e+08,state,west-bengal,2024,4

In [15]:
data2=aggregate_transaction
data2.shape

(5174, 8)

### Aggregated users

In [16]:
root_path="../pulse/data/aggregated/user/country/india"
entries=os.listdir(root_path)
aggregate_users=pd.DataFrame(columns=["appopen","usersbydevicebrand","usersbydevicecount","level","region","year","quater"])
ind=0
print(entries)
for entry in entries:
    if entry!="state":
        level="India"
        year=entry
        regionlevel="India"
        year_path=os.path.join(root_path,entry)
        files=os.listdir(year_path)
        for filename in files:
            try:
                filepath=os.path.join(year_path,filename)
                with open(filepath,"r") as f:
                    response=json.load(f)
                    obj=response["data"]
                    appopen=obj["aggregated"]["appOpens"]
                    quarter=filename.split(".")[0]
                    deviceitem=obj["usersByDevice"]
                    if deviceitem:
                        for user in deviceitem:
                            brand=user["brand"]
                            count=user["count"]
                            aggregate_users.loc[ind]=[appopen,brand,count,level,regionlevel,year,quarter]
                            ind+=1
                    else:
                        brand="Nan"
                        count="Nan"
                        aggregate_users.loc[ind]=[appopen,brand,count,level,regionlevel,year,quarter]
                        ind+=1
            except Exception as e:
                print(e)
    else:
        level="state"
        state_path=os.path.join(root_path,entry)
        states=os.listdir(state_path)
        for i in states:
            regionlevel= i
            stateinfopath=os.path.join(state_path,i)
            if os.listdir(stateinfopath):
                years=os.listdir(stateinfopath)
                for yr in years:
                    year=yr
                    year_path=os.path.join(stateinfopath,yr)
                    datas=os.listdir(year_path)
                    for files in datas:
                        try:
                            filepath=os.path.join(year_path,files)
                            with open(filepath,"r") as file:
                                response=json.load(file)
                                obj=response["data"]
                                appopen=obj["aggregated"]["appOpens"]
                                quarter=files.split(".")[0]
                                deviceitem=obj["usersByDevice"]
                                if deviceitem:
                                    for user in deviceitem:
                                        brand=user["brand"]
                                        count=user["count"]
                                        aggregate_users.loc[ind]=[appopen,brand,count,level,regionlevel,year,quarter]
                                        ind+=1
                                else:
                                    brand="Nan"
                                    count="Nan"
                                    aggregate_users.loc[ind]=[appopen,brand,count,level,regionlevel,year,quarter]
                                    ind+=1
                        except Exception as e:
                            print(e)

['2018', '2019', '2020', '2021', '2022', '2023', '2024', 'state']

In [17]:
data3=aggregate_users
data3.shape

(7326, 7)

In [18]:
data3

,appopen,usersbydevicebrand,usersbydevicecount,level,region,year,quater
0,0,Xiaomi,11926334,India,India,2018,1
1,0,Samsung,9609401,India,India,2018,1
2,0,Vivo,5894293,India,India,2018,1
3,0,Oppo,4479351,India,India,2018,1
4,0,Realme,2376866,India,India,2018,1
...,...,...,...,...,...,...,...
7321,1467442959,Nan,Nan,state,west-bengal,2023,4
7322,633526507,Nan,Nan,state,west-bengal,2024,1
7323,704276274,Nan,Nan,state,west-bengal,2024,2
7324,709864323,Nan,Nan,state,west-bengal,2024,3
7325,1994940763,Nan,Nan,state,west-bengal,2024,4

#### Loading : data loading in sql

In [19]:
import sqlalchemy
from sqlalchemy import create_engine,text

In [20]:
# %pip install pymysql

In [21]:
try:
    engine=create_engine("mysql+pymysql://root:Khush%40123@127.0.0.1:3306/phonepay")
    with engine.connect() as conn:
        print("Connected successfully!")
except Exception as e:
    print(e)

Connected successfully!

In [26]:
with engine.connect() as conn:
    conn.execute(text("create database if not exists phonepay"))
    res=conn.execute(text("use phonepay;"))
    data1.to_sql("aggregate_insurance",con=engine,if_exists="replace",index=False)
    data2.to_sql("aggregate_transaction",con=engine,if_exists="replace",index=False)
    data3.to_sql("aggregate_users",con=engine,if_exists="replace",index=False)