In [1]:
import os
import pandas as pd
import json

### Map insurance

In [2]:
# metric(insurance transaction amount)
# Lat
# long
# label(area)
# year
# region
# level
# quarter

In [3]:
root_path="../pulse/data/map/insurance/country/india"

In [4]:
os.listdir(root_path)

['2020', '2021', '2022', '2023', '2024', 'state']

##### Here we are not considering map inusrance data and we consider the hover data because the map insuarance data is just used for plotting heatmaps on the map data with lat,long,metric,label.

In [5]:
root_path = "../pulse/data/map/insurance/country/india"
rows = []
def parse_map_insurance_file(file_path: str, year: str, level: str):
    quarter = os.path.splitext(os.path.basename(file_path))[0]

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            response = json.load(f)

        records = response.get("data", {}).get("data", {}).get("data", [])

        for record in records:
            if len(record) < 4:
                continue

            latitude = record[0]
            longitude = record[1]
            insurance_transaction_amount = record[2]
            region = record[3]

            rows.append({
                "insurance_transaction_amount": insurance_transaction_amount,
                "label": region,
                "latitude": latitude,
                "longitude": longitude,
                "year": year,
                "level": level,
                "quarter": quarter
            })

    except Exception as e:
        print(f"Error processing file {file_path}: {e}")


entries = os.listdir(root_path)

for entry in entries:
    entry_path = os.path.join(root_path, entry)

    if entry == "state":
        for state in os.listdir(entry_path):
            state_path = os.path.join(entry_path, state)
            if not os.path.isdir(state_path):
                continue

            for yr in os.listdir(state_path):
                year_path = os.path.join(state_path, yr)
                if not os.path.isdir(year_path):
                    continue

                for file_name in os.listdir(year_path):
                    if not file_name.endswith(".json"):
                        continue

                    file_path = os.path.join(year_path, file_name)
                    parse_map_insurance_file(
                        file_path=file_path,
                        year=yr,
                        level="state"
                    )

    else:
        year = entry
        if not os.path.isdir(entry_path):
            continue

        for file_name in os.listdir(entry_path):
            if not file_name.endswith(".json"):
                continue

            file_path = os.path.join(entry_path, file_name)
            parse_map_insurance_file(
                file_path=file_path,
                year=year,
                level="India"
            )

map_insurance = pd.DataFrame(rows)

In [6]:
map_insurance.head()

,insurance_transaction_amount,label,latitude,longitude,year,level,quarter
0,4720.0,karnataka,12.881175,77.567674,2020,India,2
1,3186.0,telangana,17.428197,78.389911,2020,India,2
2,2753.0,karnataka,12.967107,77.475933,2020,India,2
3,2674.0,telangana,17.340345,78.480878,2020,India,2
4,2408.0,karnataka,12.885550,77.659339,2020,India,2

In [7]:
map_insurance.shape

(1430349, 7)

#### Map insurance hover data

In [8]:
#name 
#type
#count
#amount
#level
#quarter
#year

In [9]:
root_path = "../pulse/data/map/insurance/hover/country/india"
rows = []

def parse_hover_file(file_path, year, level):
    quarter = os.path.splitext(os.path.basename(file_path))[0]

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            response = json.load(f)

        hover_data = response.get("data", {}).get("hoverDataList", [])

        for item in hover_data:
            metric_list = item.get("metric", [])
            if not metric_list:
                continue

            metric = metric_list[0]

            rows.append({
                "insurance_area_name": item.get("name"),
                "map_insurance_type": metric.get("type"),
                "insurance_count": metric.get("count"),
                "insurance_amount": metric.get("amount"),
                "year": year,
                "level": level,
                "quarter": quarter
            })

    except Exception as e:
        print(f"Error in {file_path}: {e}")


entries = os.listdir(root_path)

for entry in entries:
    entry_path = os.path.join(root_path, entry)

    if entry == "state":
        states = os.listdir(entry_path)

        for state in states:
            state_path = os.path.join(entry_path, state)
            if not os.path.isdir(state_path):
                continue

            years = os.listdir(state_path)

            for yr in years:
                year_path = os.path.join(state_path, yr)
                if not os.path.isdir(year_path):
                    continue

                files = os.listdir(year_path)

                for file_name in files:
                    if file_name.endswith(".json"):
                        file_path = os.path.join(year_path, file_name)
                        parse_hover_file(file_path, yr, "state")

    else:
        year = entry
        if not os.path.isdir(entry_path):
            continue

        files = os.listdir(entry_path)

        for file_name in files:
            if file_name.endswith(".json"):
                file_path = os.path.join(entry_path, file_name)
                parse_hover_file(file_path, year, "India")

map_hover_insurance = pd.DataFrame(rows)

In [10]:
map_hover_insurance.head()

,insurance_area_name,map_insurance_type,insurance_count,insurance_amount,year,level,quarter
0,puducherry,TOTAL,112,22251.0,2020,India,2
1,tamil nadu,TOTAL,5473,1075552.0,2020,India,2
2,uttar pradesh,TOTAL,9884,1912266.0,2020,India,2
3,madhya pradesh,TOTAL,6283,1198701.0,2020,India,2
4,andhra pradesh,TOTAL,22104,3982391.0,2020,India,2

In [11]:
map_hover_insurance.shape

(14558, 7)

### Map transaction

In [12]:
root_path="../pulse/data/map/transaction/hover/country/india"
os.listdir(root_path)

['2018', '2019', '2020', '2021', '2022', '2023', '2024', 'state']

In [13]:
root_path = "../pulse/data/map/transaction/hover/country/india"
rows = []

def parse_hover_file(file_path, year, level):
    quarter = os.path.splitext(os.path.basename(file_path))[0]

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            response = json.load(f)

        hover_data = response.get("data", {}).get("hoverDataList", [])

        for item in hover_data:
            metric_list = item.get("metric", [])
            if not metric_list:
                continue

            metric = metric_list[0]

            rows.append({
                "transaction_area_name": item.get("name"),
                "map_transaction_type": metric.get("type"),
                "transaction_count": metric.get("count"),
                "transaction_amount": metric.get("amount"),
                "year": year,
                "level": level,
                "quarter": quarter
            })

    except Exception as e:
        print(f"Error in {file_path}: {e}")


entries = os.listdir(root_path)

for entry in entries:
    entry_path = os.path.join(root_path, entry)

    if entry == "state":
        states = os.listdir(entry_path)

        for state in states:
            state_path = os.path.join(entry_path, state)
            if not os.path.isdir(state_path):
                continue

            years = os.listdir(state_path)

            for yr in years:
                year_path = os.path.join(state_path, yr)
                if not os.path.isdir(year_path):
                    continue

                files = os.listdir(year_path)

                for file_name in files:
                    if file_name.endswith(".json"):
                        file_path = os.path.join(year_path, file_name)
                        parse_hover_file(file_path, yr, "state")

    else:
        year = entry
        if not os.path.isdir(entry_path):
            continue

        files = os.listdir(entry_path)

        for file_name in files:
            if file_name.endswith(".json"):
                file_path = os.path.join(entry_path, file_name)
                parse_hover_file(file_path, year, "India")

map_hover_transaction = pd.DataFrame(rows)

In [14]:
map_hover_transaction.head()

,transaction_area_name,map_transaction_type,transaction_count,transaction_amount,year,level,quarter
0,puducherry,TOTAL,104212,1.658260e+08,2018,India,1
1,tamil nadu,TOTAL,6726622,1.126156e+10,2018,India,1
2,uttar pradesh,TOTAL,12537805,1.393997e+10,2018,India,1
3,madhya pradesh,TOTAL,8025395,8.681603e+09,2018,India,1
4,andhra pradesh,TOTAL,9039585,1.199628e+10,2018,India,1

In [15]:
map_hover_transaction.shape

(21612, 7)

### Map User Data

In [16]:
root_path="../pulse/data/map/user/hover/country/india"
os.listdir(root_path)

['2018', '2019', '2020', '2021', '2022', '2023', '2024', 'state']

In [17]:
root_path = "../pulse/data/map/user/hover/country/india"
rows = []

def parse_hover_file(file_path, year, level):
    quarter = os.path.splitext(os.path.basename(file_path))[0]

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            response = json.load(f)

        hover_data = response.get("data", {}).get("hoverData", {})
        
        for k,v in hover_data.items():
            rows.append({
                "user_area_name": k,
                "user_type": v["registeredUsers"],
                "user_app_opens":v["appOpens"],
                "year": year,
                "level": level,
                "quarter": quarter
            })

    except Exception as e:
        print(f"Error in {file_path}: {e}")


entries = os.listdir(root_path)

for entry in entries:
    entry_path = os.path.join(root_path, entry)

    if entry == "state":
        states = os.listdir(entry_path)

        for state in states:
            state_path = os.path.join(entry_path, state)
            if not os.path.isdir(state_path):
                continue

            years = os.listdir(state_path)

            for yr in years:
                year_path = os.path.join(state_path, yr)
                if not os.path.isdir(year_path):
                    continue

                files = os.listdir(year_path)

                for file_name in files:
                    if file_name.endswith(".json"):
                        file_path = os.path.join(year_path, file_name)
                        parse_hover_file(file_path, yr, "state")

    else:
        year = entry
        if not os.path.isdir(entry_path):
            continue

        files = os.listdir(entry_path)

        for file_name in files:
            if file_name.endswith(".json"):
                file_path = os.path.join(entry_path, file_name)
                parse_hover_file(file_path, year, "India")

map_hover_user = pd.DataFrame(rows)

In [18]:
map_hover_user.head()

   user_area_name  user_type  user_app_opens  year  level quarter
0      puducherry      49318               0  2018  India       1
1      tamil nadu    2104754               0  2018  India       1
2   uttar pradesh    4694250               0  2018  India       1
3  madhya pradesh    2553603               0  2018  India       1
4  andhra pradesh    3336450               0  2018  India       1

In [19]:
map_hover_user.shape

(21616, 6)

In [20]:
import sqlalchemy
from sqlalchemy import create_engine,text
try:
    engine=create_engine("mysql+pymysql://root:Khush%40123@127.0.0.1:3306/phonepay")
    with engine.connect() as conn:
        print("Connected successfully!")
except Exception as e:
    print(e)

Connected successfully!

In [21]:
with engine.connect() as conn:
    conn.execute(text("create database if not exists phonepay"))
    res=conn.execute(text("use phonepay;"))
    map_insurance.to_sql("map_insurance",con=engine,if_exists="replace",index=False)
    map_hover_transaction.to_sql("map_hover_transaction",con=engine,if_exists="replace",index=False)
    map_hover_user.to_sql("map_hover_user",con=engine,if_exists="replace",index=False)