In [1]:
import os 
import json
import pandas as pd

### Top insurance

In [2]:
root_path="../pulse/data/top/insurance/country/india"
os.listdir(root_path)

['2020', '2021', '2022', '2023', '2024', 'state']

In [3]:
root_path = "../pulse/data/top/insurance/country/india"
rows = []

def parse_hover_file(file_path, year, level):
    quarter = os.path.splitext(os.path.basename(file_path))[0]

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            response = json.load(f)

        if level == "India":
            datas = response.get("data", {}).get("states", [])
        else:
            datas = response.get("data", {}).get("districts", [])

        for item in datas:
            metric = item.get("metric", {})

            rows.append({
                "top_insuarnce_region": item.get("entityName"),
                "top_insurance_type": metric.get("type"),
                "top_insurance_count": metric.get("count"),
                "top_insurance_amount": metric.get("amount"),
                "year": year,
                "level": level,
                "quarter": quarter
            })

    except Exception as e:
        print(f"Error in {file_path}: {e}")


entries = os.listdir(root_path)

for entry in entries:
    entry_path = os.path.join(root_path, entry)

    if entry == "state":
        states = os.listdir(entry_path)

        for state in states:
            state_path = os.path.join(entry_path, state)
            if not os.path.isdir(state_path):
                continue

            years = os.listdir(state_path)

            for yr in years:
                year_path = os.path.join(state_path, yr)
                if not os.path.isdir(year_path):
                    continue

                files = os.listdir(year_path)

                for file_name in files:
                    if file_name.endswith(".json"):
                        file_path = os.path.join(year_path, file_name)
                        parse_hover_file(file_path, yr, "state")

    else:
        year = entry
        if not os.path.isdir(entry_path):
            continue

        files = os.listdir(entry_path)
        for file_name in files:
            if file_name.endswith(".json"):
                file_path = os.path.join(entry_path, file_name)
                parse_hover_file(file_path, year, "India")

top_inurance = pd.DataFrame(rows)

In [4]:
top_inurance.tail()

,top_insuarnce_region,top_insurance_type,top_insurance_count,top_insurance_amount,year,level,quarter
5793,paschim bardhaman,TOTAL,4945,7005851.0,2024,state,4
5794,paschim medinipur,TOTAL,4155,5405054.0,2024,state,4
5795,malda,TOTAL,4042,4902098.0,2024,state,4
5796,nadia,TOTAL,3807,5031294.0,2024,state,4
5797,purba bardhaman,TOTAL,3595,4482879.0,2024,state,4

In [5]:
top_inurance.shape

(5798, 7)

### Top transaction

In [6]:
root_path = "../pulse/data/top/transaction/country/india"
os.listdir(root_path)

['2018', '2019', '2020', '2021', '2022', '2023', '2024', 'state']

In [7]:
root_path = "../pulse/data/top/transaction/country/india"
rows = []

def parse_hover_file(file_path, year, level):
    quarter = os.path.splitext(os.path.basename(file_path))[0]

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            response = json.load(f)

        if level == "India":
            datas = response.get("data", {}).get("states", [])
        else:
            datas = response.get("data", {}).get("districts", [])

        for item in datas:
            metric = item.get("metric", {})

            rows.append({
                "top_region": item.get("entityName"),
                "top_type": metric.get("type"),
                "top_count": metric.get("count"),
                "top_amount": metric.get("amount"),
                "year": year,
                "level": level,
                "quarter": quarter
            })

    except Exception as e:
        print(f"Error in {file_path}: {e}")


entries = os.listdir(root_path)

for entry in entries:
    entry_path = os.path.join(root_path, entry)

    if entry == "state":
        states = os.listdir(entry_path)

        for state in states:
            state_path = os.path.join(entry_path, state)
            if not os.path.isdir(state_path):
                continue

            years = os.listdir(state_path)

            for yr in years:
                year_path = os.path.join(state_path, yr)
                if not os.path.isdir(year_path):
                    continue

                files = os.listdir(year_path)

                for file_name in files:
                    if file_name.endswith(".json"):
                        file_path = os.path.join(year_path, file_name)
                        parse_hover_file(file_path, yr, "state")

    else:
        year = entry
        if not os.path.isdir(entry_path):
            continue

        files = os.listdir(entry_path)
        for file_name in files:
            if file_name.endswith(".json"):
                file_path = os.path.join(entry_path, file_name)
                parse_hover_file(file_path, year, "India")

top_transactions = pd.DataFrame(rows)

In [8]:
top_transactions.head()

       top_region top_type  top_count    top_amount  year  level quarter
0     maharashtra    TOTAL   16387034  2.171161e+10  2018  India       1
1   uttar pradesh    TOTAL   12537805  1.393997e+10  2018  India       1
2       karnataka    TOTAL   12016899  1.921790e+10  2018  India       1
3     west bengal    TOTAL   11710225  1.062598e+10  2018  India       1
4  andhra pradesh    TOTAL    9039585  1.199628e+10  2018  India       1

In [9]:
top_transactions.shape

(8576, 7)

### Top user

In [10]:
root_path = "../pulse/data/top/user/country/india"
os.listdir(root_path)

['2018', '2019', '2020', '2021', '2022', '2023', '2024', 'state']

In [11]:
import os
import json
import pandas as pd

root_path = "../pulse/data/top/user/country/india"
rows = []

def parse_hover_file(file_path, year, level, state_name=None):
    quarter = os.path.splitext(os.path.basename(file_path))[0]

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            response = json.load(f)

        data = response.get("data", {})

        # parse states
        states = data.get("states") or []
        for item in states:
            rows.append({
                "region_type": "state",
                "region_name": item.get("name"),
                "registered_users": item.get("registeredUsers"),
                "year": year,
                "level": level,
                "parent_state": state_name if state_name else "India",
                "quarter": quarter
            })

        # parse districts
        districts = data.get("districts") or []
        for item in districts:
            rows.append({
                "region_type": "district",
                "region_name": item.get("name"),
                "registered_users": item.get("registeredUsers"),
                "year": year,
                "level": level,
                "parent_state": state_name if state_name else "India",
                "quarter": quarter
            })

    except Exception as e:
        print(f"Error in {file_path}: {e}")


entries = os.listdir(root_path)

for entry in entries:
    entry_path = os.path.join(root_path, entry)

    if entry == "state":
        states = os.listdir(entry_path)

        for state in states:
            state_path = os.path.join(entry_path, state)
            if not os.path.isdir(state_path):
                continue

            years = os.listdir(state_path)

            for yr in years:
                year_path = os.path.join(state_path, yr)
                if not os.path.isdir(year_path):
                    continue

                files = os.listdir(year_path)

                for file_name in files:
                    if file_name.endswith(".json"):
                        file_path = os.path.join(year_path, file_name)
                        parse_hover_file(file_path, yr, "State", state)

    else:
        year = entry
        if not os.path.isdir(entry_path):
            continue

        files = os.listdir(entry_path)
        for file_name in files:
            if file_name.endswith(".json"):
                file_path = os.path.join(entry_path, file_name)
                parse_hover_file(file_path, year, "India")

top_users = pd.DataFrame(rows)

In [12]:
top_users.tail()

,region_type,region_name,registered_users,year,level,parent_state,quarter
8851,district,hooghly,1957356,2024,State,west-bengal,4
8852,district,nadia,1861738,2024,State,west-bengal,4
8853,district,purba medinipur,1717074,2024,State,west-bengal,4
8854,district,paschim medinipur,1522845,2024,State,west-bengal,4
8855,district,paschim bardhaman,1468252,2024,State,west-bengal,4

In [13]:
top_users.shape

(8856, 7)

In [14]:
import sqlalchemy
from sqlalchemy import create_engine,text

In [15]:
try:
    engine=create_engine("mysql+pymysql://root:Khush%40123@127.0.0.1:3306/phonepay")
    with engine.connect() as conn:
        print("Connected successfully!")
except Exception as e:
    print(e)

Connected successfully!

In [16]:
with engine.connect() as conn:
    conn.execute(text("create database if not exists phonepay"))
    res=conn.execute(text("use phonepay;"))
    top_inurance.to_sql("top_insurance",con=engine,if_exists="replace",index=False)
    top_transactions.to_sql("top_transactions",con=engine,if_exists="replace",index=False)
    top_users.to_sql("top_users",con=engine,if_exists="replace",index=False)